### ISSUE TITLE
Update Communities.Json

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/dash-cc#8]
Shift structure to (roughly):

```json
{
   "numerical_id": {
      "name": "community name",
      "region": "province/state",
      "latlng": [lat, lng]
   },

   "123": {
      "name": "Fairbanks",
      "region": "Alaska",
      "latlng": [65, -150]
   },

   "456": {
      "name": "Xax'lip",
      "region": "British Columbia",
      "latlng": [123, 234]
   }
...
}
```

And, ensure that the character encoding is UTF-8 and is preserving Unicode glyphs where appropriate.  With these changes, we can:

 * Decouple user input from filesystem traversal,
 * Show the region name,
 * put things on a map if appropriate.

**Comment by cstephen** [comment]
I have structured the `CommunityNames.json` file during the 2021 revamp to something that more closely resembles what was described in this issue, but omitting lat/lon coordinates since they are not used in the web app, and including alternate names for communities when they exist. I will close this issue once this work is merged.
